services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5039:5039"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=5039
    depends_on:
      api.postgres:
        condition: service_healthy

  api.postgres:
    image: postgres:16.9-alpine
    container_name: api.postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "banking_solution"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d banking_solution"]
      interval: 5s
      timeout: 3s
      retries: 5
